export const BLOG = process.env.PUBLIC_URL + '/blog'
export const HOME = process.env.PUBLIC_URL + '/' 
export const LOGIN = process.env.PUBLIC_URL + '/login'
export const LOGOUT = process.env.PUBLIC_URL + '/logout'
export const ADD_POST = process.env.PUBLIC_URL + '/add'